export enum ShopActionTypes {
  FETCH_PRODUCTS_BY_TYPE = 'FETCH_PRODUCTS_BY_TYPE',
  FETCH_PRODUCTS_BY_QUERY = 'FETCH_PRODUCTS_BY_QUERY',

  FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS',
  FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE',

  FILTER_PRODUCTS = 'FILTER_PRODUCTS'
}
