export enum UserActionTypes {
  CHECK_SESSION = 'CHECK_SESSION',

  SIGN_IN_START = 'SIGN_IN_START',
  SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE = 'SIGN_IN_FAILURE',

  SIGN_UP_START = 'SIGN_UP_START',
  SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS',
  SIGN_UP_FAILURE = 'SIGN_UP_FAILURE',

  SIGN_OUT = 'SIGN_OUT',

  CLEAR_ERRORS = 'CLEAR_ERRORS'
}
